### ISSUE TITLE
Getting "PLS-00201: identifier 'UT_DOCUMENTATION_REPORTER' must be declared" when executing from UTPLSQL CLI

### ISSUE THREAD

**Issue by venkat-kasula** [utPLSQL/utPLSQL#1119]
Hi All, 

I am new to utPLSQL and I have been assigned the task to check the feasibility of integrating utPLSQL for unit testing in our development environment. I have installed UTPLSQL on my test env(AWS RDS) and i m trying to run from the UTPLSQL CLI. i m getting below error . Kindly help me out to resolve the issue. 

**Note :** If i am executing from the SQL Developer, eveything is fine & able to generate the report. 

**works fine in SQL Developer**
```
set serveroutput on size unlimited
set feedback off
spool atest.html 
exec ut3.ut.run( ut3.ut_coverage_html_reporter(),a_color_console => true)
spool off
```
But when i m trying the same from the UTPLSQL CLI, i m facing below error:
Command used:
utplsql run <connection params> -p=venkat.ut_add_contestant -f=ut_documentation_reporter -o=run.log -s -f=ut_coverage_html_reporter -o=coverage.html -source_path=source

Successfully connected to database. UtPLSQL core: v3.1.10.3349
Oracle-Version: 18.0.0.0.0
java.sql.SQLException: ORA-06550: line 1, column 13:
PLS-00201: identifier 'UT_DOCUMENTATION_REPORTER' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored

        at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1168)
        at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:1065)
        at oracle.jdbc.driver.T2CCallableStatement.executeForDescribe(T2CCallableStatement.java:764)
        at oracle.jdbc.driver.T2CCallableStatement.executeForRows(T2CCallableStatement.java:1007)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
        at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
        at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
        at org.utplsql.api.reporter.Reporter.initDbReporter(Reporter.java:72)
        at org.utplsql.api.reporter.Reporter.init(Reporter.java:46)
        at org.utplsql.cli.ReporterManager.initReporters(ReporterManager.java:95)
        at org.utplsql.cli.RunAction.initReporters(RunAction.java:219)
        at org.utplsql.cli.RunAction.doRun(RunAction.java:70)
        at org.utplsql.cli.RunAction.run(RunAction.java:121)
        at org.utplsql.cli.RunPicocliCommand.run(RunPicocliCommand.java:254)
        at org.utplsql.cli.Cli.runPicocliWithExitCode(Cli.java:44)
        at org.utplsql.cli.Cli.main(Cli.java:13)
Caused by: Error : 6550, Position : 12, Sql = BEGIN :1 := UT_DOCUMENTATION_REPORTER(); END;, OriginalSql = {? = call UT_DOCUMENTATION_REPORTER()}, Error Msg = ORA-06550: line 1, column 13:
PLS-00201: identifier 'UT_DOCUMENTATION_REPORTER' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored

Kindly help me to resolve the issue.

**Comment by pesse** [comment]
Hey @venkat-kasula ,
it looks like you haven't set up the synonyms properly for the user you want to use (since you're using `ut3.ut.run` instead of `ut.run`).
Please check the documentation: http://utplsql.org/utPLSQL/latest/userguide/install.html#allowing-other-users-to-access-the-utplsql-framework

CLI needs the synonyms to work properly.

Best regards,
Samuel

**Comment by venkat-kasula** [comment]
> Hey @venkat-kasula ,
> it looks like you haven't set up the synonyms properly for the user you want to use (since you're using `ut3.ut.run` instead of `ut.run`).
> Please check the documentation: http://utplsql.org/utPLSQL/latest/userguide/install.html#allowing-other-users-to-access-the-utplsql-framework
> 
> CLI needs the synonyms to work properly.
> 
> Best regards,
> Samuel

Thnx ALot it worked#:+1:

**Comment by venkat-kasula** [comment]
But i m facing this issue again 

TestRunner initialized
Running on utPLSQL v3.1.10.3349
Initializing reporters
Detected Oracle driver stuck during Statement initialization
WARNING: Caught Oracle stuck during creation of Runner-Statement. Retrying (1)
############################## utPLSQL cli ##############################
#                                                                       #
#   utPLSQL-cli 3.1.8-SNAPSHOT.local                                    #
#   utPLSQL-java-api 3.1.8.546                                          #
#   Java-Version: 1.8.0_121                                             #
#   ORACLE_HOME:    #
#   NLS_LANG: null                                                      #
#                                                                       #
#   Thanks for testing!                                                 #
#                                                                       #
#########################################################################

Use connection string jdbc:oracle:oci8:****/****@******:**/**
Successfully connected to database. UtPLSQL core: v3.1.10.3349
Oracle-Version: 18.0.0.0.0
Running tests now.
--------------------------------------
TestRunner initialized
Running on utPLSQL v3.1.10.3349
Initializing reporters
Detected Oracle driver stuck during Statement initialization
