### ISSUE TITLE
Release files of utPLSQL 3.1.12 are lacking version number in package specification UT_UTILS.GC_VERSION

### ISSUE THREAD

**Issue by db-geek** [utPLSQL/utPLSQL#1190]
**Describe the bug**
Today tested the new release **3.1.12** from [utPLSQL releases](https://github.com/utPLSQL/utPLSQL/releases).
I installed this new release in an containerized Oracle database and executed my tests using **utPLSQL-cli 3.1.8**.

But the execution of **utPLSQL-cli 3.1.8** failed with following error:
```
2022-02-24 20:41:40 [main] INFO  org.utplsql.cli.RunAction - ##################### utPLSQL cli #####################
#                                                     #
#   utPLSQL-cli 3.1.8-SNAPSHOT.local                  #
#   utPLSQL-java-api 3.1.8.546                        #
#   Java-Version: 17.0.1                              #
#   ORACLE_HOME: /opt/portable/oracle/instantclient   #
#   NLS_LANG: AMERICAN_AMERICA.UTF8                   #
#                                                     #
#   Thanks for testing!                               #
#                                                     #
#######################################################
2022-02-24 20:41:40 [main] INFO  org.utplsql.cli.RunAction - 
2022-02-24 20:41:40 [main] DEBUG o.u.c.d.TestedDataSourceProvider - NLS settings: BEGIN
EXECUTE IMMEDIATE q'[ALTER SESSION SET NLS_LANGUAGE='AMERICAN']';
EXECUTE IMMEDIATE q'[ALTER SESSION SET NLS_TERRITORY='AMERICA']';
END;
2022-02-24 20:41:41 [main] INFO  o.u.c.d.TestedDataSourceProvider - Use connection string jdbc:oracle:thin:****/****@******:1521/******
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at org.utplsql.api.Version.create(Version.java:75)
        at org.utplsql.api.db.DefaultDatabaseInformation.getUtPlsqlFrameworkVersion(DefaultDatabaseInformation.java:18)
        at org.utplsql.api.compatibility.CompatibilityProxy.<init>(CompatibilityProxy.java:61)
        at org.utplsql.api.compatibility.CompatibilityProxy.<init>(CompatibilityProxy.java:45)
        at org.utplsql.api.compatibility.CompatibilityProxy.<init>(CompatibilityProxy.java:40)
        at org.utplsql.cli.RunAction.checkFrameworkCompatibility(RunAction.java:267)
        at org.utplsql.cli.RunAction.initDatabase(RunAction.java:190)
        at org.utplsql.cli.RunAction.doRun(RunAction.java:69)
        at org.utplsql.cli.RunAction.run(RunAction.java:121)
        at org.utplsql.cli.RunPicocliCommand.run(RunPicocliCommand.java:254)
        at org.utplsql.cli.Cli.runPicocliWithExitCode(Cli.java:44)
        at org.utplsql.cli.Cli.main(Cli.java:13)
```
After some investigation, I found that the constant **GC_VERSION** in the package specification of **UT_UTILS** is not set.
This is problem is only available in the release files [utPLSQL.tar.gz](https://github.com/utPLSQL/utPLSQL/releases/download/v3.1.12/utPLSQL.tar.gz) and [utPLSQL.zip](https://github.com/utPLSQL/utPLSQL/releases/download/v3.1.12/utPLSQL.zip).

After setting of **UT_UTILS.GC_VERSION** to **v3.1.12.3876** from [Release source code v3.1.12.tar.gz](https://github.com/utPLSQL/utPLSQL/archive/refs/tags/v3.1.12.tar.gz) the execution of tests with **utPLSQL-cli 3.1.8** was successful again.

**Provide version info**
Information about utPLSQL and Database version:
```sql
SQL> set serveroutput on
SQL> declare
  2    l_version varchar2(255);
  3    l_compatibility varchar2(255);
  4  begin
  5    dbms_utility.db_version( l_version, l_compatibility );
  6    dbms_output.put_line( l_version );
  7    dbms_output.put_line( l_compatibility );
  8  end;
  9* /
21.0.0.0.0
21.0.0

SQL> select substr(ut.version(),1,60) as ut_version from dual;

   UT_VERSION 
_____________ 
              

SQL> select * from v$version;

                                                                BANNER                                                                               BANNER_FULL                                                          BANNER_LEGACY    CON_ID 
______________________________________________________________________ _________________________________________________________________________________________ ______________________________________________________________________ _________ 
Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production    Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0    Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production            0 

SQL> select * from nls_session_parameters;

                 PARAMETER                           VALUE 
__________________________ _______________________________ 
NLS_LANGUAGE               AMERICAN                        
NLS_TERRITORY              AMERICA                         
NLS_CURRENCY               $                               
NLS_ISO_CURRENCY           AMERICA                         
NLS_NUMERIC_CHARACTERS     .,                              
NLS_CALENDAR               GREGORIAN                       
NLS_DATE_FORMAT            DD-MON-RR                       
NLS_DATE_LANGUAGE          AMERICAN                        
NLS_SORT                   BINARY                          
NLS_TIME_FORMAT            HH.MI.SSXFF AM                  
NLS_TIMESTAMP_FORMAT       DD-MON-RR HH.MI.SSXFF AM        
NLS_TIME_TZ_FORMAT         HH.MI.SSXFF AM TZR              
NLS_TIMESTAMP_TZ_FORMAT    DD-MON-RR HH.MI.SSXFF AM TZR    
NLS_DUAL_CURRENCY          $                               
NLS_COMP                   BINARY                          
NLS_LENGTH_SEMANTICS       BYTE                            
NLS_NCHAR_CONV_EXCP        FALSE                           


SQL> select substr(dbms_utility.port_string,1,60) as port_string from dual;

           PORT_STRING 
______________________ 
x86_64/Linux 2.4.xx
```

**Information about client software**
What client was used to run utPLSQL tests?
**utPLSQL-cli 3.1.8**

**To Reproduce**
1. Download release files [utPLSQL.tar.gz](https://github.com/utPLSQL/utPLSQL/releases/download/v3.1.12/utPLSQL.tar.gz) or [utPLSQL.zip](https://github.com/utPLSQL/utPLSQL/releases/download/v3.1.12/utPLSQL.zip)
2. Extract release file to local directory
3. Install _utPLS_ software in Oracle database
4. Execute _utPLS_ database unit tests with **utPLSQL-cli 3.1.8**.

**Expected behavior**
Running of utPLSQL database unit tests with **utPLSQL-cli 3.1.8** is not failing with _**java.lang.NullPointerException**_.

**Example code**
Package **ut_utils**:

```
  gc_version                 constant varchar2(50) := 'v3.1.12.3876';
```

**Comment by jgebal** [comment]
We will need to re-release version 3.1.12 - thanks for the feedback

**Comment by jgebal** [comment]
Fun with moving release and test automation between providers.
This is now resolved. Release was fixed.
Please download again.
