### ISSUE TITLE
ORA-00904 when running Maven

### ISSUE THREAD

**Issue by pnoga70** [utPLSQL/utPLSQL#665]
Hello,

we use utPLSQL v3 (v3.0.4.1372) for unit testing of our Oracle PL/SQL code. We would like to call our unit tests from Maven. We downloaded utPLSQL-maven-plugin and configured it, but when we run Maven we get the following error message.

[INFO] Invoking TestRunner with: r:\project.db.nasdb.utplsql\target
[info] Writing report UT_COVERAGE_SONAR_REPORTER to r:\project.db.nasdb.utplsql\target\utplsql\coverage-sonar-reporter.xml
[info] Writing report UT_COVERAGE_SONAR_REPORTER to Console
[ERROR] Unexpected error opening file ouput
org.apache.maven.plugin.MojoExecutionException: Unexpected error opening file ouput
        at org.utplsql.reporter.ReporterWriter.writeReports(ReporterWriter.java:100)
        at org.utplsql.reporter.ReporterWriter.writeReporters(ReporterWriter.java:49)
        at org.utplsql.UtPLSQLMojo.execute(UtPLSQLMojo.java:144)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "UT_OUTPUT_BUFFER"."GET_LINES": neplatný identifikátor
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:747)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
        at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
        at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3822)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1165)
        at org.utplsql.api.OutputBuffer.fetchAvailable(OutputBuffer.java:71)
        at org.utplsql.api.OutputBuffer.printAvailable(OutputBuffer.java:53)
        at org.utplsql.reporter.ReporterWriter.writeReports(ReporterWriter.java:96)
        ... 24 more
Caused by: Error : 904, Position : 20, Sql = SELECT * FROM table(ut_output_buffer.get_lines(:1 )), OriginalSql = SELECT * FROM table(ut_output_buffer.get_lines(?)), Error Msg = ORA-00904: "UT_OUTPUT_BUFFER"."GET_LINES": neplatný identifikátor
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
        ... 41 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36.255 s
[INFO] Finished at: 2018-05-11T09:05:27+02:00
[INFO] Final Memory: 9M/22M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.utplsql:utplsql-maven-plugin:1.0.0-SNAPSHOT:test (run-tests) on project db.nasdb: Execution run-tests of
goal org.utplsql:utplsql-maven-plugin:1.0.0-SNAPSHOT:test failed. NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

We don't know why we get Oracle ORA-00904 error. Package UT_OUTPUT_BUFFER on our database exists (in UT3 schema), it has (public) GET_LINES function. The package is granted to PUBLIC, the "SELECT * FROM table(ut_output_buffer.get_lines(:1 ))" SQL query can be run under various database users without any exception (although it returns nothing and just waits).

Can you, please, help us? (We are not sure at which layer (database, Maven plugin, ...) the problem is.) Thank you.

**Comment by jgebal** [comment]
Maven plugin was not yet officially released. It is not complete and is not compatible with utPLSQL 3.1.0 and above.

**Comment by pnoga70** [comment]
Thank you for the information. I have two questions.

1. When do you expect official release of utPLSQL v3 Maven plugin?
2. We still use utPLSQL 3.0.4. Does it help?

**Comment by jgebal** [comment]
@pnoga70 I strongly encourage to update to latest utPLSQL v3.1.1
For maven plugin - I'm not involved in development of that project so have no timeline on release dates.
It is best to raise such questions directly on maven plugin project.

**Comment by jgebal** [comment]
I'm closing this issue as separate issue was opened in maven-plugin repo.
