### ISSUE TITLE
frequently ORA-01013 errors

### ISSUE THREAD

**Issue by tkleiber** [utPLSQL/utPLSQL#915]
With the new versions I get frequently follwing errors, which I did not see 3.1.3 before.

`
/data/utPLSQL-cli/bin/utplsql run ****/****@****:****/****--color --path=****,****--failure-exit-code=0 --timeout=240 --format=ut_documentation_reporter -o=ut_documentation_reporter_db.log -s --format=ut_xunit_reporter -o=ut_xunit_reporter.xml --format=ut_coverage_html_reporter -o=ut_coverage_html_reporter.html
Picked up _JAVA_OPTIONS: -Duser.language=en

\########## utPLSQL cli ###########
\#                                \#
\#   utPLSQL-cli 3.1.6.local      \#
\#   utPLSQL-java-api 3.1.6.411   \#
\#   Java-Version: 1.8.0_66       \#
\#   ORACLE_HOME: null            \#
\#   NLS_LANG: null               \#
\#                                \#
\#   Thanks for testing!          \#
\#                                #
\##################################

Use connection string jdbc:oracle:thin:****/****@****:****/****
Successfully connected to database. UtPLSQL core: v3.1.6.2735
Oracle-Version: 11.2.0.4.0
java.sql.SQLTimeoutException: ORA-01013: Benutzer hat Abbruch des aktuellen Vorgangs angefordert
ORA-06512: in "UT3.UT_OUTPUT_TABLE_BUFFER", Zeile 198
ORA-06512: in "UT3.UT_OUTPUT_TABLE_BUFFER", Zeile 24
ORA-06512: in "UT3.UT_OUTPUT_REPORTER_BASE", Zeile 27
ORA-06512: in "UT3.UT_XUNIT_REPORTER", Zeile 21
ORA-06512: in Zeile 1
ORA-06512: in Zeile 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1052)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:537)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:255)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:610)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:249)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:82)
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:924)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1136)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3640)
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1318)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3752)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4242)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
	at org.utplsql.api.outputBuffer.OutputBufferProvider.hasOutput(OutputBufferProvider.java:67)
	at org.utplsql.api.outputBuffer.OutputBufferProvider.getCompatibleOutputBuffer(OutputBufferProvider.java:33)
	at org.utplsql.api.compatibility.CompatibilityProxy.getOutputBuffer(CompatibilityProxy.java:169)
	at org.utplsql.api.reporter.DefaultReporter.initOutputBuffer(DefaultReporter.java:21)
	at org.utplsql.api.reporter.Reporter.init(Reporter.java:51)
	at org.utplsql.cli.ReporterManager.initReporters(ReporterManager.java:90)
	at org.utplsql.cli.RunCommand.initReporters(RunCommand.java:296)
	at org.utplsql.cli.RunCommand.doRun(RunCommand.java:157)
	at org.utplsql.cli.RunCommand.run(RunCommand.java:216)
	at org.utplsql.cli.Cli.runWithExitCode(Cli.java:42)
	at org.utplsql.cli.Cli.main(Cli.java:14)
Caused by: Error : 1013, Position : 0, Sql = declare    l_result int;begin    begin        execute immediate '       begin            :x := case ' || dbms_assert.simple_sql_name( :1  ) || '() is of (ut_output_reporter_base) when true then 1 else 0 end;       end;'       using out l_result;   end;   :2  := l_result;end;, OriginalSql = declare    l_result int;begin    begin        execute immediate '       begin            :x := case ' || dbms_assert.simple_sql_name( ? ) || '() is of (ut_output_reporter_base) when true then 1 else 0 end;       end;'       using out l_result;   end;   ? := l_result;end;, Error Msg = ORA-01013: Benutzer hat Abbruch des aktuellen Vorgangs angefordert
ORA-06512: in "UT3.UT_OUTPUT_TABLE_BUFFER", Zeile 198
ORA-06512: in "UT3.UT_OUTPUT_TABLE_BUFFER", Zeile 24
ORA-06512: in "UT3.UT_OUTPUT_REPORTER_BASE", Zeile 27
ORA-06512: in "UT3.UT_XUNIT_REPORTER", Zeile 21
ORA-06512: in Zeile 1
ORA-06512: in Zeile 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 25 more
`

**Comment by pesse** [comment]
Done. Thanks for the tip - learned something new today :)

**Comment by jgebal** [comment]
Hi @tkleiber, 
Would you be able to install utPLSQL 3.1.7-develop (from our develop branch)?
There were following fixes done to the output buffer table after 3.1.6:
1. separated `clob` buffer table from `varchar2` buffer table. `varchar2` is default for most reporters (as it used to be)
2. `clob` buffer table has it's storage changed to enable in-row storage for small clob data (up to 4k)

With those two improvements, you should not see the timeout anymore.
One thing to consider though would be why did you end up with polluted buffer. It seems that your previous runs were not finishing cleanly and the data was not flushed from the buffer.

From what I remember, your schema is quite big and the coverage reports were quite heavy which would fit to the number of rows left in buffer.

**Comment by tkleiber** [comment]
Have installed v3.1.7.29.28-develop. Will see if the error goes away in the next days, as it was not reproducible at will.

Sometimes I see before follwoing error in cli call too, but not in the direct call before the error happens:

Finished in 1363,215123 seconds
1407 tests, 57 failed, 181 errored, 5 disabled, 1 warning(s)
**Timeout while waiting for reporters to finish for 240 minutes**

**Comment by tkleiber** [comment]
In the last 10 days nether the ORA-1013 nor the Timeout error happens with v3.1.7.29.28-develop!
